@startuml diagrama de despliegue

skinparam Linetype ortho
'left to right direction
skinparam ArrowThickness 2
skinparam componentBorderThickness 1
skinparam padding 1
skinparam componentMinHeight 1
skinparam componentFontSize 22

' node GestorHechos as "node" {
'     component Hechos
' }

cloud servicioExterno
database Hechos_y_Solicitudes

node node as "Fuente Estatica" {
    component modelo as cosa3{
        component Fuentes as Fuentes
        component Parsers as Parsers
    }

    component API as API1
    file Dataset

    Fuentes --> Parsers
    Parsers --> Dataset
    API1 --> Fuentes
}

node node1 as "Fuente Proxy" {
    component modelo as cosa2{
        component Fuentes as Fuentes2
        component Parsers as Parsers2
    }
    component API as API2

    Fuentes2 --> Parsers2
    API2 --> Fuentes2
    Parsers2 --> servicioExterno
}

node node2 as "Fuente Dinamica" {
    component modelo as cosa1{
        component Fuentes as Fuentes3
        component Solicitudes
    }
    component API as API3
    component UI_SolicitudesEliminacion
    component UI_SolicitudesEdicion

    API3 --> Fuentes3
    Solicitudes --> Fuentes3
    UI_SolicitudesEdicion --> Solicitudes
    UI_SolicitudesEliminacion --> Solicitudes
    Fuentes3 --> Hechos_y_Solicitudes
}

database Hechos_y_Solicitudes as HyS

node node3 as "Agregador"{
    component modelo{
        component Agregacion as Agregador1
        component Fuentes as Fuentes4
        component Solicitudes as Soli2
    }

    component UI_SolicitudesEliminacion as UI_solisEl
    component UI_SolicitudesEdicion as UI_solisED
    
    UI_solisED --> Soli2
    UI_solisEl --> Soli2

    Agregador1 --> Soli2
    Soli2 --> Fuentes4
    Agregador1 --> Fuentes4
    Fuentes4 --> API1
    Fuentes4 --> API2
    Fuentes4 --> API3
    modelo--> HyS

}

@enduml