@startuml diagrama de componentes
skinparam Linetype ortho
'left to right direction
skinparam ArrowThickness 2
skinparam componentBorderThickness 1
'skinparam padding 1
skinparam componentMinHeight 1
skinparam componentFontSize 24
skinparam packageFontSize 20


[FuenteDeDatos] -(0- [Parsers] 
[FuenteDeDatos] -0)- [Agregacion]
[Agregacion] -0)- [Colecciones]
[Incidencias] -0)- [FuenteDeDatos] 
[Incidencias] -0)- [Agregacion]
[FuenteDeDatos] -0)- [Agregacion]
[Solicitudes] -0)- [Agregacion]
[Solicitudes] -0)- [FuenteDeDatos]
[Usuarios] -0)- [Solicitudes]
[Usuarios] -0)- [Incidencias]

component Incidencias{
    [Hecho]
    package ControlMultimedia{
        [Multimedia]
        [TipoMultimedia]
    }
    package Ubicaciones
    [Hecho] --> Ubicaciones
    [Hecho] --> ControlMultimedia
}


component Colecciones{
    [Coleccion]
    package Criterios{
    [CriterioFecha]
    [CriterioTitulo]
    [CriterioDescripcion]
    [CriterioCategoria]
    [CriterioUbicacion]
    [CriterioOrigen]
    [CriterioMultimedia]
    }
    [Coleccion] --> Criterios
}

component Agregacion{
    [Agregador]
}

component FuenteDeDatos{
    [FuenteEstatica]
    [FuenteProxy]
    [FuenteDinamica]
}

component Usuarios{
    [perfil]
    [usuario]
    [Rol]
    [usuario] --> [perfil]
    [usuario] --> [Rol]
}

component Solicitudes{
    package solicitudesDeEliminacion{
        [solicitudEliminacion]
    }
    package solicitudesDeEdicion{
        [solicitudEdicion]
    }
    [EstadoSolicitud]
    [detectorDeSpam]
    solicitudesDeEliminacion --> [detectorDeSpam]
    solicitudesDeEliminacion --> [EstadoSolicitud]
    solicitudesDeEdicion --> [EstadoSolicitud]
}

component Parsers{
    [JSONHechoParser]
    [CSVHechoParser]
}


@enduml